#### Perceptron is an one-layer neural network
#### Linear Binary Classfier
#### 1. Input layer
#### 2. Weight and Bias: output = a weighted average of features <-- bias generated
#### 3. Weighted Sum
#### 4. Activation Function: run in each unit. in perceptron, y = m(x)+b

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [4]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10]    # predictive features

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [5]:
# split train and test datasets 20%, 80%

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
# Standize variables

standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

standardized_X_test[0:10]

array([[ 0.56682896,  0.47841158,  1.34758617,  1.78079681],
       [ 1.03271577, -0.2513688 ,  0.79978691,  0.76802137],
       [-0.48141638,  0.7216717 , -1.11751048, -0.87773871],
       [-0.36494467, -1.71092954,  0.14242781,  0.0084398 ],
       [ 0.21741385, -0.98114917,  0.85456684,  0.64142444],
       [-1.41319001,  0.7216717 , -1.17229041, -1.00433564],
       [ 0.45035725, -0.49462892,  0.41632743,  0.26163365],
       [ 0.56682896, -1.46766942,  0.79978691,  1.02121523],
       [-0.94730319,  0.7216717 , -1.11751048, -1.13093257],
       [ 2.19743281, -0.2513688 ,  1.40236609,  1.52760295]])

In [7]:
# call the model and fit the data

perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(alpha=0.0001, class_weight=None, early_stopping=False, eta0=0.15,
           fit_intercept=True, max_iter=50, n_iter_no_change=5, n_jobs=None,
           penalty=None, random_state=15, shuffle=True, tol=0.001,
           validation_fraction=0.1, verbose=0, warm_start=False)

In [8]:
y_pred = perceptron.predict(standardized_X_test)

In [9]:
print(y_test)

[2 1 0 1 1 0 1 2 0 2 0 0 2 1 2 0 2 1 0 1 1 1 1 0 0 0 1 0 2 0]


In [10]:
print(y_pred)

[2 2 0 1 2 0 1 2 0 2 0 0 2 1 2 0 2 1 0 1 1 1 1 0 0 0 1 0 2 0]


In [11]:
# get accuracy

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        12
           1       1.00      0.82      0.90        11
           2       0.78      1.00      0.88         7

    accuracy                           0.93        30
   macro avg       0.93      0.94      0.92        30
weighted avg       0.95      0.93      0.93        30

